function parallelCases()
{
  var name = document.getElementById("fname").innerHTML;
  ajaxCall99(name,table);
//ajaxCall9();
//ajaxCall10();
ajaxCall11(name,table);
ajaxCall15(name,table);
//ajaxCall18();
//ajaxCall19();
//ajaxCall20();
//ajaxCall21();
ajaxCall22(name,table);
ajaxCall28(name,table);
ajaxCall34(name,table);
//ajaxCall35();
ajaxCall36(name,table);
//ajaxCall37();
//ajaxCall38();
ajaxCall39(name,table);
//ajaxCall40();
//ajaxCall41();
//ajaxCall42();
//ajaxCall43();
//ajaxCall44();
ajaxCall55(name,table);
//ajaxCall56();
//ajaxCall57();
//ajaxCall58();
//ajaxCall59();
//ajaxCall60();
//ajaxCall61();
//ajaxCall62();
//ajaxCall63();
ajaxCall91(name,table);
}
