version: 1.0
runners:
  high:
    config-id: 3
jobs:
  catalyst-deploy:
    steps:
      - npm install -g zcatalyst-cli
      - catalyst deploy
stages:
  - name: deploy
    runner: high
    jobs:
      - catalyst-deploy