version: 1
pipeline-when:
  equal:
    - << event.ref >>
    - << env.BRANCH_NAME >>
runners:
  high:
    config-id: 3
jobs:
  catalyst-deploy:
    steps:
      - npm install -g zcatalyst-cli@beta
      - catalyst deploy
stages:
  - name: deploy
    runner: high
    jobs:
      - catalyst-deploy