version: 1.0
runners:
  high:
    config-id: 3
images:
    jdk:
        image: maven:3.8.5-openjdk-17
        auth:
            username: vipinkumarh
            password: << env.DOCKER_PASS >> 
jobs:
  catalyst-deploy:
    steps:
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
      - microdnf install -y nodejs
      - npm install -g zcatalyst-cli@beta
      - printenv
      - catalyst deploy --verbose
stages:
  - name: deploy
    runner: high
    image: jdk
    jobs:
      - catalyst-deploy