version: 1
pipeline-when:
  equal:
    - << event.ref >>
    - << env.BRANCH_NAME >>
runners:
  high:
    config-id: 3
jobs:
  catalyst-deploy:
    steps:
      - npm install -g zcatalyst-cli@beta
      - catalyst deploy
stages:
  - name: deploy
    runner: high
    jobs:
      - catalyst-deploy
variables:
  CATALYST_TOKEN: 1004.fcbbb0c781da2425deb1557a2492f4dd.45ae8dfad4523ba302394468dc9b55dd
  BRANCH_NAME: ConnectorTest